---
- hosts: localhost
  become: yes
  tasks:
    - name: Install development libraries and tools
      import_playbook: 00_install_libraries.yml

    - name: Install packages
      import_playbook: 01_install_packages.yml

    - name: Install fonts
      import_playbook: 02_install_fonts.yml

    - name: Install gnome extensions
      import_playbook: 03_install_gnome_extensions.yml

    - name: Configure gnome
      import_playbook: 04_configure_gnome.yml

    - name: Install mise
      import_playbook: 05_install_mise.yml

    # Asus specific
    - name: Check if the computer is an ASUS
      set_fact:
        is_asus: "{{ 'ASUSTeK' in ansible_facts['manufacturer'] }}"

    - name: Install ASUS tools (if this is an ASUS computer)
      import_playbook: 06_setup_asus.yml
      when: is_asus